

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

    restart: always

  api:
    build: .
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mongodb
    volumes:
      - .:/app